fix
git remote add origin-token https://[secure]@github.com/sustainsb/sustainsb.github.io.git
To https://[secure]@github.com/sustainsb/sustainsb.github.io.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://[secure]@github.com/sustainsb/sustainsb.github.io.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
The command "./_push.sh" exited with 1.